[config]
reload_apps = true
set_wallpaper = false

[config.reload_apps_list]
waybar = false
kitty = false
gtk_theme = false
dunst = false

[config.custom_colors]
red = { color = "#ff474c", blend = false }
orange = { color = "#fdaa48", blend = false }
yellow = { color = "#ffd700", blend = false }
green = { color = "#90ee90", blend = false }
blue = { color = "#addfff", blend = false }
cyan = { color = "#acfffc", blend = false }
purple = { color = "#bf77f6", blend = false }
magenta = { color = "#ffd1df", blend = false }

[templates]
kitty = {input_path = '~/.config/matugen/templates/kitty_colors.template', output_path = '~/.config/kitty/colorschemes/matugen.conf'}
konsole = {input_path = '~/.config/matugen/templates/konsole_colors.template', output_path = '~/.local/share/konsole/matugen.colorscheme'}

fuzzel = {input_path = '~/.config/matugen/templates/fuzzel_colors.template', output_path = '~/.config/fuzzel/colors/matugen.ini'}
dmenu = {input_path = '~/.config/matugen/templates/dmenu_xresources_colors.template', output_path = '~/.config/dmenu/xcolors_dmenu/matugen'}
rofi = {input_path = '~/.config/matugen/templates/rofi_colors.template', output_path = '~/.config/qtile/external_configs/rofi/colorschemes/matugen.rasi'}

ags = {input_path = '~/.config/matugen/templates/ags_colors.template', output_path = '~/.config/hypr/external_configs/ags/themes/roundish_circle/styles/colorscheme_matugen.json'}
dwm = {input_path = '~/.config/matugen/templates/dwm_xresources_colors.template', output_path = '~/.config/dwm/xcolors_dwm/matugen'}
luastatus_colors = {input_path = '~/.config/matugen/templates/luastatus_colors.template', output_path = '~/.config/dwm/luastatus/colorscheme/helper/matugen_colors.lua'}
luastatus_modules = {input_path = '~/.config/matugen/templates/luastatus_modules_colors.template', output_path = '~/.config/dwm/luastatus/colorscheme/matugen.lua'}

zathura = {input_path = '~/.config/matugen/templates/zathura.template', output_path = '~/.config/zathura/colorschemes/matugen'}

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk_colors.template'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk_colors.template'
output_path = '~/.config/gtk-4.0/gtk.css'
