const colorschemes_vars = {
  catppuccin_macchiato: {
    label_fg: "#cad3f5",
    bar_bg: "#181926",
    clock_container_bg: "#363a4f",
    clock_icon_bg: "#f5a97f",
    clock_icon_fg: "#181926",
    clock_label_fg: "#f5a97f",
    clock_border: "#f5a97f",
    window_title_border: "#cad3f5",
    workspace_item_active_icon_bg: "#ee99a0",
    workspace_item_active_icon_fg: "#181926",
    workspace_item_active_container_bg: "#24273a",
    workspace_item_active_label_fg: "#ee99a0",
    workspace_border: "#ee99a0",
    systray_bg: "#494d64",
    battery_container_bg: "#363a4f",
    battery_container_charging_bg: "#363a4f",
    battery_label_fg: "#a6da95",
    battery_label_charging_fg: "#ed8796",
    battery_icon_fg: "#363a4f",
    battery_icon_bg: "#a6da95",
    battery_icon_charging_bg: "#ed8796",
    battery_border: "#a6da95",
    battery_border_charging: "#ed8796",

    bar_opacity: "0.8",

    hyprland_border: "ee99a0",
  },
  dracula: {
    label_fg: "#f8f8f2",
    bar_bg: "#282a36",
    clock_container_bg: "#44475a",
    clock_icon_bg: "#8be9fd",
    clock_icon_fg: "#282a36",
    clock_label_fg: "#8be9fd",
    clock_border: "#8be9fd",
    window_title_border: "#f8f8f2",
    workspace_item_active_icon_bg: "#bd93f9",
    workspace_item_active_icon_fg: "#282a36",
    workspace_item_active_container_bg: "#44475a",
    workspace_item_active_label_fg: "#bd93f9",
    workspace_border: "#bd93f9",
    systray_bg: "#6272a4",
    battery_container_bg: "#44475a",
    battery_container_charging_bg: "#44475a",
    battery_label_fg: "#ffb86c",
    battery_label_charging_fg: "#ff5555",
    battery_icon_fg: "#363a4f",
    battery_icon_bg: "#ffb86c",
    battery_icon_charging_bg: "#ff5555",
    battery_border: "#ffb86c",
    battery_border_charging: "#ff5555",

    bar_opacity: "0.8",

    hyprland_border: "bd93f9",
  },
  everblush: {
    label_fg: "#dadada",
    bar_bg: "#141b1e",
    clock_container_bg: "#232a2d",
    clock_icon_bg: "#e5c76b",
    clock_icon_fg: "#232a2d",
    clock_label_fg: "#e5c76b",
    clock_border: "#e5c76b",
    window_title_border: "#d3c6aa",
    workspace_item_active_icon_bg: "#8ccf7e",
    workspace_item_active_icon_fg: "#141b1e",
    workspace_item_active_container_bg: "#232a2d",
    workspace_item_active_label_fg: "#8ccf7e",
    workspace_border: "#8ccf7e",
    systray_bg: "#232a2d",
    battery_container_bg: "#232a2d",
    battery_container_charging_bg: "#232a2d",
    battery_label_fg: "#6cbfbf",
    battery_label_charging_fg: "#e57474",
    battery_icon_fg: "#141b1e",
    battery_icon_bg: "#6cbfbf",
    battery_icon_charging_bg: "#e57474",
    battery_border: "#6cbfbf",
    battery_border_charging: "#e57474",

    bar_opacity: "0.8",

    hyprland_border: "8ccf7e",
  },
  everforest: {
    label_fg: "#d3c6aa",
    bar_bg: "#272e33",
    clock_container_bg: "#374145",
    clock_icon_bg: "#e69875",
    clock_icon_fg: "#374145",
    clock_label_fg: "#e69875",
    clock_border: "#e69875",
    window_title_border: "#d3c6aa",
    workspace_item_active_icon_bg: "#a7c080",
    workspace_item_active_icon_fg: "#3c4848",
    workspace_item_active_container_bg: "#3c4848",
    workspace_item_active_label_fg: "#a7c080",
    workspace_border: "#a7c080",
    systray_bg: "#414b50",
    battery_container_bg: "#384b55",
    battery_container_charging_bg: "#4c3743",
    battery_label_fg: "#7fbbb3",
    battery_label_charging_fg: "#e67e79",
    battery_icon_fg: "#384b55",
    battery_icon_bg: "#7fbbb3",
    battery_icon_charging_bg: "#e67e79",
    battery_border: "#7fbbb3",
    battery_border_charging: "#e67e79",

    bar_opacity: "0.8",

    hyprland_border: "a7c080",
  },
  gruvbox: {
    label_fg: "#ebdbb2",
    bar_bg: "#282828",
    clock_container_bg: "#3c3836",
    clock_icon_bg: "#d65d0e",
    clock_icon_fg: "#3c3836",
    clock_label_fg: "#fe8019",
    clock_border: "#d65d0e",
    window_title_border: "#ebdbb2",
    workspace_item_active_icon_bg: "#98971a",
    workspace_item_active_icon_fg: "#3c3836",
    workspace_item_active_container_bg: "#3c3836",
    workspace_item_active_label_fg: "#98971a",
    workspace_border: "#98971a",
    systray_bg: "#504945",
    battery_container_bg: "#3c3836",
    battery_container_charging_bg: "#3c3836",
    battery_label_fg: "#fabd2f",
    battery_label_charging_fg: "#fb4934",
    battery_icon_fg: "#3c3836",
    battery_icon_bg: "#d79921",
    battery_icon_charging_bg: "#cc241d",
    battery_border: "#d79921",
    battery_border_charging: "#cc241d",

    bar_opacity: "0.8",

    hyprland_border: "98971a",
  },
  horizon: {
    label_fg: "#FAC29A",
    bar_bg: "#1A1C23",
    clock_container_bg: "#2E303E",
    clock_icon_bg: "#E95678",
    clock_icon_fg: "#1A1C23",
    clock_label_fg: "#E95678",
    clock_border: "#E95678",
    window_title_border: "#FAC29A",
    workspace_item_active_icon_bg: "#F09383",
    workspace_item_active_icon_fg: "#1A1C23",
    workspace_item_active_container_bg: "#2E303E",
    workspace_item_active_label_fg: "#F09383",
    workspace_border: "#F09383",
    systray_bg: "#6C6F93",
    battery_container_bg: "#2E303E",
    battery_container_charging_bg: "#1A1C23",
    battery_label_fg: "#29D398",
    battery_label_charging_fg: "#E95678",
    battery_icon_fg: "#2E303E",
    battery_icon_bg: "#29D398",
    battery_icon_charging_bg: "#E95678",
    battery_border: "#29D398",
    battery_border_charging: "#E95678",

    bar_opacity: "0.8",

    hyprland_border: "98971a",
  },
  nord: {
    label_fg: "#d8dee9",
    bar_bg: "#2e3440",
    clock_container_bg: "#3b4252",
    clock_icon_bg: "#d08770",
    clock_icon_fg: "#2e3440",
    clock_label_fg: "#d08770",
    clock_border: "#d08770",
    window_title_border: "#d8dee9",
    workspace_item_active_icon_bg: "#81a1c1",
    workspace_item_active_icon_fg: "#2e3440",
    workspace_item_active_container_bg: "#3b4252",
    workspace_item_active_label_fg: "#81a1c1",
    workspace_border: "#81a1c1",
    systray_bg: "#434c5e",
    battery_container_bg: "#3b4252",
    battery_container_charging_bg: "#3b4252",
    battery_label_fg: "#a3be8c",
    battery_label_charging_fg: "#bf616a",
    battery_icon_fg: "#2e3440",
    battery_icon_bg: "#a3be8c",
    battery_icon_charging_bg: "#bf616a",
    battery_border: "#a3be8c",
    battery_border_charging: "#bf616a",

    bar_opacity: "0.8",

    hyprland_border: "81a1c1",
  },
  rose_pine: {
    label_fg: "#e0def4",
    bar_bg: "#191724",
    clock_container_bg: "#26233a",
    clock_icon_bg: "#c4a7e7",
    clock_icon_fg: "#26233a",
    clock_label_fg: "#c4a7e7",
    clock_border: "#c4a7e7",
    window_title_border: "#e0def4",
    workspace_item_active_icon_bg: "#d7827e",
    workspace_item_active_icon_fg: "#26233a",
    workspace_item_active_container_bg: "#26233a",
    workspace_item_active_label_fg: "#d7827e",
    workspace_border: "#d7827e",
    systray_bg: "#403d52",
    battery_container_bg: "#26233a",
    battery_container_charging_bg: "#26233a",
    battery_label_fg: "#f6c177",
    battery_label_charging_fg: "#eb6f92",
    battery_icon_fg: "#26233a",
    battery_icon_bg: "#f6c177",
    battery_icon_charging_bg: "#eb6f92",
    battery_border: "#f6c177",
    battery_border_charging: "#eb6f92",

    bar_opacity: "0.8",

    hyprland_border: "d7827e",
  },
  tokyonight_storm: {
    label_fg: "#c0caf5",
    bar_bg: "#24283b",
    clock_container_bg: "#292e42",
    clock_icon_bg: "#bb9af7",
    clock_icon_fg: "#292e42",
    clock_label_fg: "#bb9af7",
    clock_border: "#bb9af7",
    window_title_border: "#e0def4",
    workspace_item_active_icon_bg: "#7aa2f7",
    workspace_item_active_icon_fg: "#26233a",
    workspace_item_active_container_bg: "#26233a",
    workspace_item_active_label_fg: "#7aa2f7",
    workspace_border: "#7aa2f7",
    systray_bg: "#403d52",
    battery_container_bg: "#26233a",
    battery_container_charging_bg: "#26233a",
    battery_label_fg: "#41a6b5",
    battery_label_charging_fg: "#f7768e",
    battery_icon_fg: "#26233a",
    battery_icon_bg: "#41a6b5",
    battery_icon_charging_bg: "#f7768e",
    battery_border: "#41a6b5",
    battery_border_charging: "#f7768e",

    bar_opacity: "0.8",

    hyprland_border: "7aa2f7",
  },
};

export const get_colors_vars = (selected_colorscheme = "gruvbox") => {
  if (selected_colorscheme == "matugen") {
    const user_options = JSON.parse(
      Utils.readFile(`${App.configDir}/user_options.json`),
    );

    const matugen_colors = JSON.parse(
      Utils.readFile(
        `${App.configDir}/themes/${user_options.theme}/styles/colorscheme_matugen.json`,
      ),
    );

    return matugen_colors;
  } else {
    return colorschemes_vars[selected_colorscheme];
  }
};
