# --- main ---
# ------------

source = ~/.config/mango/configs/autostart.conf
source = ~/.config/mango/configs/env_vars.conf

source = ~/.config/mango/configs/inputs.conf
source = ~/.config/mango/configs/monitors.conf
source = ~/.config/mango/configs/layouts.conf

source = ~/.config/mango/configs/general.conf
source = ~/.config/mango/configs/tags.conf
source = ~/.config/mango/configs/styles.conf
source = ~/.config/mango/configs/animations.conf

source = ~/.config/mango/configs/rules_layer.conf
source = ~/.config/mango/configs/rules_client.conf

source = ~/.config/mango/configs/keybindings.conf
