# --- animations ---
# ------------------

animations                  =     1
layer_animations            =     1

animation_type_open         = slide
animation_type_close        = slide
layer_animation_type_open   = slide
layer_animation_type_close  = slide

animation_fade_in           =     0
animation_fade_out          =     1

tag_animation_direction     =     0

zoom_initial_ratio          =   0.5
zoom_end_ratio              =   0.9

fadein_begin_opacity        =   0.5
fadeout_begin_opacity       =   0.5

animation_duration_move     =   500
animation_duration_open     =   400
animation_duration_tag      =   500
animation_duration_close    =   600
animation_duration_focus    =   400

animation_curve_open        =   0.2, 0.0, 0.0, 1.0
animation_curve_move        =   0.2, 0.0, 0.0, 1.0
animation_curve_tag         =   0.2, 0.0, 0.0, 1.0
animation_curve_close       =   0.2, 0.0, 0.0, 1.0
