# --- autostart ---
# -----------------

# authentication agent
exec-once = systemctl --user start hyprpolkitagent

# wallpaper
exec-once = swww-daemon

# screenshare
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots

# desktop shell
exec-once = qs

# input method
exec-once=fcitx5 -d

# clipboard
exec-once = sleep 1 && wl-paste --type text --watch cliphist store
exec-once = sleep 1 && wl-paste --type image --watch cliphist store

# input method
exec-once = fcitx5 -d

# bluelight filter
exec-once = sunsetr --background
