# --- general ---
# ---------------

# overview
# --------
#
enable_hotarea = 0
hotarea_size = 10

ov_tab_mode = 0

overviewgappi = 20
overviewgappo = 20

# scratchpad
# ----------
#
scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.9

# misc
# ----
#
no_border_when_single = 0

axis_bind_apply_timeout = 100
focus_on_activate = 1
inhibit_regardless_of_visibility = 0

drag_tile_to_tile = 1

sloppyfocus = 1
focus_cross_monitor = 0
focus_cross_tag = 0

enable_floating_snap = 1
snap_distance = 30

warpcursor = 1
cursor_size = 32
