# --- input ---
# -------------


# keyboard
# --------
#
repeat_rate = 25
repeat_delay = 600

numlockon = 1

xkb_rules_layout = us, us
xkb_rules_variant = dvorak, 
xkb_rules_options = caps:escape, grp:shifts_toggle, grp_led:caps

# trackpad
# --------
#
disable_trackpad = 0

tap_to_click = 1
tap_and_drag = 1

drag_lock = 1
trackpad_natural_scrolling = 0

disable_while_typing = 1
left_handed = 0
middle_button_emulation = 0
swipe_min_threshold = 1

# mouse
# -----
#
mouse_natural_scrolling = 0
