# --- layouts ---
# ---------------

circle_layout = scroller,vertical_scroller,vertical_tile

# scroller layout
# ---------------
#
scroller_structs = 20
scroller_default_proportion = 0.95

scroller_focus_center = 0
scroller_prefer_center = 0

edge_scroller_pointer_focus = 0

scroller_ignore_proportion_single = 1
scroller_default_proportion_single = 1.00

# widths that "switch_proportion_preset" toggles between
scroller_proportion_preset = 0.25, 0.50, 0.75, 1.00

# master-stack layout
# -------------------
#
new_is_master = 0

default_mfact = 0.55
default_nmaster = 1

smartgaps = 0
