# --- styles ---
# --------------

borderpx = 3
border_radius = 0
no_radius_when_single = 0

focused_opacity = 0.90
unfocused_opacity = 0.85

gappih = 10
gappiv = 10
gappoh = 10
gappov = 10

# colors
# ------
#
rootcolor = 0x201b14ff
bordercolor = 0x00000000
focuscolor = 0x999999ff
maxmizescreencolor = 0x89aa61ff
urgentcolor = 0xad401fff
scratchpadcolor = 0x516c93ff
globalcolor = 0xb153a7ff
overlaycolor = 0x14a57cff

# blur
# ----
#
blur = 1
blur_layer = 0
blur_optimized = 1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

# shadow
# ------
#
shadows = 0
layer_shadows = 0
shadow_only_floating = 1
shadows_size = 10
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor = 0x000000ff
