#!/usr/bin/env bash

# Directory
dwm_dir="$HOME/.config/dwm"
dmenu_dir="$HOME/.config/dmenu"
dwm_luastatus_dir="$HOME/.config/dwm/luastatus/colorscheme"
alacritty_dir="$HOME/.config/alacritty"
kitty_dir="$HOME/.config/kitty"
zathura_dir="$HOME/.config/zathura"

prompt="dmenu -l 9 "
#prompt="rofi -dmenu"

# for restarting dwm
dwm_pid="$(pidof dwm)"

# Theme
cancel="窱 Cancel"
theme1=" Cozy-Night"
theme2=" Dracula"
theme3=" Gruvbox"
theme4=" Nord"

# Variable to pass to dmenu or rofi
option="$cancel\n$theme1\n$theme2\n$theme3\n$theme4"


theme_change()
{
	cp ${dwm_dir}/theme_xresources/$1 ${dwm_dir}/theme_xresources/theme
	cp ${dmenu_dir}/theme_xresources/$1 ${dmenu_dir}/theme_xresources/theme
	cp ${dwm_luastatus_dir}/$1.lua ${dwm_luastatus_dir}/color.lua
	
	cp ${alacritty_dir}/colorscheme/$1.yml ${alacritty_dir}/color.yml
	cp ${kitty_dir}/colorscheme/$1.conf ${kitty_dir}/color.conf
	cp ${zathura_dir}/theme/$1 ${zathura_dir}/theme.color
	
	if [[ "$1" == "cozy-night" ]]; then
    # vim
		sed -i "0,/colorscheme/{s/\(colorscheme\)\(.*\)/colorscheme tokyonight/}" .vimrc
		sed -i "0,/'colorscheme'/{s/\('colorscheme':\)\(.*\)/\ 'colorscheme': 'tokyonight',/}" .vimrc

    # nvim
		sed -i "0,/colorscheme/{s/\(colorscheme\)\(.*\)/colorscheme tokyonight/}" ~/.config/nvim/lua/colorscheme.lua
	else
    # vim
		sed -i "0,/colorscheme/{s/\(colorscheme\)\(.*\)/colorscheme $1/}" .vimrc
		sed -i "s/\('colorscheme':\)\(.*\)/'colorscheme': '$1',/" .vimrc

    # nvim
		sed -i "0,/colorscheme/{s/\(colorscheme\)\(.*\)/colorscheme $1/}" ~/.config/nvim/lua/colorscheme.lua
	fi

	#make -s -C ${dwm_dir} clean
	#bash $HOME/.bin/sudo_passhelper make -s -C ${dwm_dir} install
	#make -s -C ${dwm_dir} clean
	
	xrdb -merge -I$HOME ~/.Xresources # reload Xresources
	#kill -HUP dwmpid $dwm_pid # restart dwm

  # calls xrdb function in dwm
  xsetroot -name "fsignal:2"
  # update luastatus
  kill -9 $(pidof luastatus)

	#make -s -C ${dwm_dir}/dmenu clean
	#bash $HOME/.bin/sudo_passhelper make -s -C ${dmenu_dir} install
	#make -s -C ${dmenu_dir} clean
}

select="$(echo -e "$option" | $prompt -p "Choose a theme: " )"
case $select in
	$theme1)
		feh --bg-fill $HOME/.config/wallpaper/pixelart_night_train_cozy_gas.png
		theme_change cozy-night
		;;
	$theme2)
		feh --bg-fill $HOME/.config/wallpaper/pixelart_arabian_palace_princess.png
		theme_change dracula
		;;
	$theme3)
		feh --bg-fill $HOME/.config/wallpaper/pixelart_house_inside_girl_book_dog.png
		theme_change gruvbox
		;;
	$theme4)
		feh --bg-fill $HOME/.config/wallpaper/pixelart_medicine_flower_reminder_nord.png
		theme_change nord
		;;
	esac
