[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[mode]
normal_main = { fg = "black", bg = "blue" }
normal_alt = { fg = "black", bg = "red" }

unset_main = { fg = "black", bg = "yellow" }
unset_alt = { fg = "black", bg = "red" }
