# --- autostart ---
# -----------------

# authentication agent
exec-once = systemctl --user start hyprpolkitagent

# wallpaper
exec-once = swww-daemon

# desktop shell
# exec-once = sleep 1 && agsv1 -c ~/.config/hypr/external_configs/ags_v1/config.js
exec-once = sleep 1 && qs

# clipboard
exec-once = sleep 1 && wl-paste --type text --watch cliphist store
exec-once = sleep 1 && wl-paste --type image --watch cliphist store

# input method
exec-once = fcitx5 -d

# bluelight filter
exec-once = sunsetr --background

exec-once = sleep 1 && hypridle
