# --- general ---
# ---------------

$border_active_color = rgba(bbbbbbdd)
$border_inactive_color = rgba(202020bb)
$rounding = 15

# wiki: https://wiki.hyprland.org/Configuring/Variables/#general
general {
  gaps_in = 5
  gaps_out = 8

  border_size = 2

  # wiki: https://wiki.hyprland.org/Configuring/Variables/#variable-types
  col.active_border = $border_active_color
  # col.inactive_border = $border_inactive_color
 
  resize_on_border = true # set to true enable resizing windows by clicking
                          # and dragging on borders and gaps

  # wiki: https://wiki.hyprland.org/Configuring/Tearing/
  allow_tearing = false # check wiki before turning this on

  layout = master
}

ecosystem {
  no_update_news = true
  no_donation_nag = true
}

# wiki: https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  rounding = $rounding

  # change transparency of focused and unfocused windows
  active_opacity = 0.90
  inactive_opacity = 0.65
  fullscreen_opacity = 1.0

  # dim_special = 0.0

  shadow {
    enabled = false
  }

  # wiki -> https://wiki.hyprland.org/Configuring/Variables/#blur
  blur {
    enabled = true
    passes = 2
    new_optimizations = true
    ignore_opacity = true 
    xray = false # if enabled, floating windows will ignore tiled windows in
                 # their blur
    special = false
    popups = false
    input_methods = false
  }
}

# wiki: https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
  font_family = "Iosevka Slab"

  exit_window_retains_fullscreen = true # if `true`, then it doesn't exit
                                        # maximized mode when closing a window 

  force_default_wallpaper = 0 # set to 0 or 1 to disable the anime mascot
                              # wallpapers

  disable_hyprland_logo = true # disables the random hyprland logo / anime
                               # background

  vfr = true # controls the VFR status of Hyprland

  focus_on_activate = false
}
