# --- input ---
# -------------

gestures {
  # workspace_swipe = true
  workspace_swipe_invert = false
  workspace_swipe_distance = 300
  workspace_swipe_cancel_ratio = 0.1
}

input {
  kb_layout = us,us
  kb_variant = dvorak,
  kb_model =
  kb_options = caps:escape,grp:shifts_toggle,grp_led:caps
  kb_rules =

  follow_mouse = 2

  sensitivity = 0.3

  touchpad {
    natural_scroll = false
  }
}

device {
  name = epic-mouse-v1
  # sensitivity = -0.5
}
