# --- workspaces ---
# ------------------

workspace = 1, defaultName:term
workspace = 2, defaultName:editor
workspace = 3, defaultName:file
workspace = 4, defaultName:browser
workspace = 5, defaultName:media
workspace = 6, defaultName:books
workspace = 7, defaultName:social
workspace = 8, defaultName:settings
workspace = 9, defaultName:misc
