require("widgets.app_launcher")
require("widgets.client_count")
require("widgets.battery")
--require("widgets.brightness")
require("widgets.date")
require("widgets.inbuilt_widgets")
require("widgets.layout_indicator")
require("widgets.mainmenu")
require("widgets.separator")
require("widgets.taglist")
-- require("widgets.tasklist")
require("widgets.time")
require("widgets.tray")
require("widgets.popup_tasklist")
