/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cyclelayouts.h"
#include "fsignal.h"
#include "placemouse.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftviewclients.h"
#include "stacker.h"
#include "togglefullscreen.h"
#include "toggletopbar.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

