#!/usr/bin/env bash

# Directory
dwm_dir="$HOME/.config/dwm"
dmenu_dir="$HOME/.config/dmenu"
dwm_luastatus_dir="$HOME/.config/dwm/luastatus/colorscheme"
alacritty_dir="$HOME/.config/alacritty"
kitty_dir="$HOME/.config/kitty"
zathura_dir="$HOME/.config/zathura"

# launcher
prompt="rofi -dmenu -i -theme ~/.config/rofi/script_menu.rasi"

# for restarting dwm
dwm_pid="$(pidof dwm)"

# Theme
cancel="窱 Cancel"
theme1=" Catppuccin (Macchiato)"
theme2=" Cozy-Night"
theme3=" Dracula"
theme4=" Gruvbox"
theme5=" Nord"


change_theme()
{
	cp ${dwm_dir}/theme_xresources/$1 ${dwm_dir}/theme_xresources/theme
	#cp ${dmenu_dir}/theme_xresources/$1 ${dmenu_dir}/theme_xresources/theme
	cp ${dwm_luastatus_dir}/$1.lua ${dwm_luastatus_dir}/color.lua
	
	cp ${alacritty_dir}/colorscheme/$1.yml ${alacritty_dir}/color.yml
	cp ${kitty_dir}/colorscheme/$1.conf ${kitty_dir}/color.conf
	cp ${zathura_dir}/theme/$1 ${zathura_dir}/theme.color
	
	xrdb -merge -I$HOME ~/.Xresources # reload Xresources

  # calls xrdb function in dwm
  xsetroot -name "fsignal:2"
  # update luastatus
  kill -9 $(pidof luastatus)
}
change_gtk_theme() 
{
   sed -e "s/^gtk-theme-name=.*/gtk-theme-name="$@"/" -i ~/.config/gtk-3.0/settings.ini
   sed -e "s/^gtk-theme-name=.*/gtk-theme-name=\""$@"\"/" -i ~/.gtkrc-2.0 
}
change_wzterm_colorscheme()
{
	sed -i "/color_scheme/s/ = ".*"/ = \"$1\",/" -i $HOME/.config/wezterm/wezterm.lua

}
change_rofi_theme()
{
  sed "s/\.config\/rofi\/colors.*.rasi/\.config\/rofi\/colors\/$1.rasi/" -i ~/.config/rofi/launcher.rasi
  sed "s/\.config\/rofi\/colors.*.rasi/\.config\/rofi\/colors\/$1.rasi/" -i ~/.config/rofi/script_menu.rasi
  sed "s/\.config\/rofi\/colors.*.rasi/\.config\/rofi\/colors\/$1.rasi/" -i ~/.config/rofi/script_menu_1.rasi
}
change_nvim_theme()
{
  sed "/theme/s/ = ".*"/ = \"$1\",/" -i $HOME/.config/nvim/lua/custom/chadrc.lua
}
change_btop_theme()
{
  sed -e "s@color_theme = .*@color_theme = \"$HOME/.config/btop/themes/$1.theme\"@" -i $HOME/.config/btop/btop.conf
}

# Variable to pass to dmenu or rofi
option="$cancel\n$theme1\n$theme2\n$theme3\n$theme4\n$theme5"

select="$(echo -e "$option" | $prompt -p "Choose a theme" )"

case $select in
  $theme1)
		feh --bg-fill --randomize $HOME/.config/wallpaper/pixelart_night_stars_clouds_trees_cozy_PixelArtJourney.png $HOME/.config/wallpaper/pixelart_evening_trees_pole_wires_makrustic.png $HOME/.config/wallpaper/pixelart_france_house_police-car.jpg $HOME/.config/wallpaper/pixelart_pokemon_rayquaza_forest.png
		change_theme catppuccin_macchiato
    change_gtk_theme Catppuccin
    change_wzterm_colorscheme "Catppuccin Mocha"
    change_rofi_theme catppuccin
    change_nvim_theme catppuccin
    change_btop_theme catppuccin_macchiato
		;;
	$theme2)
		feh --bg-fill $HOME/.config/wallpaper/pixelart_night_train_cozy_gas_RoyalNaym.png
		change_theme cozy-night
		change_gtk_theme TokyoNight
    change_wzterm_colorscheme "tokyonight"
    change_rofi_theme tokyonight
    change_nvim_theme tokyonight
    change_btop_theme tokyo-night
		;;
	$theme3)
		feh --bg-fill --randomize $HOME/.config/wallpaper/pixelart_arabian_palace_princess_snakepixel.png $HOME/.config/wallpaper/pixelart_winter_hut_deer_man_dog_hunt_PixelArtJourney.png
		change_theme dracula
		change_gtk_theme Dracula
    change_wzterm_colorscheme "Dracula"
    change_rofi_theme dracula
    change_nvim_theme chadracula
    change_btop_theme dracula
    ;;
	$theme4)
		feh --bg-fill --randomize $HOME/.config/wallpaper/pixelart_house_inside_girl_book_dog_jmw327.png $HOME/.config/wallpaper/pixelart_forest_camp_children_maolow-paoPao.jpg $HOME/.config/wallpaper/pixelart_house_chibi_person_game_jmw327.png $HOME/.config/wallpaper/pixelart_house_girl_string_cozy.png
		change_theme gruvbox
		change_gtk_theme Gruvbox-Dark
    change_wzterm_colorscheme "Gruvbox Dark"
    change_rofi_theme gruvbox
    change_nvim_theme gruvbox
    change_btop_theme gruvbox_dark
		;;
	$theme5)
		feh --bg-fill --randomize $HOME/.config/wallpaper/pixelart_medicine_flower_reminder_nord_Ansitru.png $HOME/.config/wallpaper/pixelart_night_train_cozy_gas_nord_RoyalNaym.png $HOME/.config/wallpaper/pixelart_mountain $HOME/.config/wallpaper/mist_forest_nord.jpg
		change_theme nord
		change_gtk_theme Nord
    change_wzterm_colorscheme "nord"
    change_rofi_theme nord
    change_nvim_theme nord
    change_btop_theme nord
		;;
	esac
