/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "fsignal.c"
#include "placemouse.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shiftviewclients.c"
#include "stacker.c"
#include "togglefullscreen.c"
#include "toggletopbar.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

