# --- main ---
# ------------

source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env_vars.conf

source = ~/.config/hypr/configs/inputs.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/layouts.conf

source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/animations.conf

source = ~/.config/hypr/configs/rules_layer.conf
source = ~/.config/hypr/configs/rules_client.conf

source = ~/.config/hypr/configs/keybindings.conf
