#-------------------------------//
#---------- variables ----------//
#-------------------------------//

# wiki -> https://wiki.hyprland.org/Configuring/Keywords/

$rounding = 15

$border_active_color = rgba(bbbbbbdd)
$border_inactive_color = rgba(202020bb)
